name: Rename Folder Oneforall to TEAMZYRO 
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  rename_folder_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Rename folder Oneforall to TEAMZYRO 
        run: |
          # Ensure the folder exists before trying to rename it
          if [ -d "Oneforall" ]; then
            mv Oneforall TEAMZYRO 
            find . -type f -name "*.py" -exec sed -i 's/Oneforall/TEAMZYRO/g' {} +
          else
            echo "Folder Oneforall does not exist."
          fi
      - name: Commit changes
        run: |
          git config --global user.name 'TeamZyro'
          git config --global user.email 'harshmanjhi0004@users.noreply.github.com'
          git add .
          git commit -m "Initial commit " || echo "No changes to commit"
          git push
