name: Replace Oneforall with TEAMZYRO
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  replace_and_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10.x'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
      - name: Replace text in .py files
        run: |
          find . -type f -name "*.py" -exec sed -i 's/Oneforall/TEAMZYRO/g' {} +
      - name: Commit changes
        run: |
          git config --global user.name 'TeamZyro
          git config --global user.email 'harshmanjhi0004@users.noreply.github.com'
          git add .
          git commit -m "Initial commit " || echo "No changes to commit"
          git push
